# -*- coding: utf-8 -*-
"""Week 3 Sales Data analysis code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vnrEVEuH9yGVOruMMOEvbjFqDFFetrFe
"""

# ==========================================
# SALES DATA ANALYSIS USING PANDAS
# ==========================================

# Import required libraries
import pandas as pd
from google.colab import files

# ------------------------------------------
# Step 1: Upload the CSV File
# ------------------------------------------
print("Please upload the sales_data.csv file.")

uploaded = files.upload()

# ------------------------------------------
# Step 2: Read the Dataset
# ------------------------------------------
df = pd.read_csv("sales_data.csv")

# Display the first 5 rows
print("\nDataset Preview:")
print(df.head())

# ------------------------------------------
# Step 3: Check for Missing Values
# ------------------------------------------
print("\nMissing Values in Each Column:")
print(df.isnull().sum())

# Remove rows with missing values
df = df.dropna()

print("\nMissing values have been removed.")

# ------------------------------------------
# Step 4: Calculate Sales Metrics
# ------------------------------------------

# Total Sales
total_sales = df["Total_Sales"].sum()

# Total Quantity Sold
total_quantity = df["Quantity"].sum()

# Average Sales
average_sales = df["Total_Sales"].mean()

# Best Selling Product
best_product = df.groupby("Product")["Quantity"].sum().idxmax()

# Number of Products Sold
number_of_products = df["Product"].nunique()

# ------------------------------------------
# Step 5: Generate Sales Report
# ------------------------------------------

print("\n")
print("=" * 40)
print("        SALES ANALYSIS REPORT")
print("=" * 40)

print("Total Sales Revenue      :", total_sales)
print("Total Quantity Sold      :", total_quantity)
print("Average Sale Amount      :", round(average_sales, 2))
print("Best Selling Product     :", best_product)
print("Number of Products       :", number_of_products)

print("=" * 40)
print("Analysis Completed Successfully!")
print("=" * 40)